name: Build, Format, and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    container:
      image: bestbunsintown/my-esp-image:latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # Step 2: Run entrypoint script
      - name: Run build script
        run: /app/entrypoint.sh
