name: Build, Format, and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-format:
    runs-on: ubuntu-latest
  
    container:
      image: bestbunsintown\my-esp-image:latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 3: Log in to Docker Hub (optional, if you need to push images)
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        run:  idf.py build


  formatting:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Step 2: Install the needed packages for formating
      - name: Set up Clang-format
        run: sudo apt-get install -y clang-format
      
      # Step 3: Run the formatter
      - name: Run Clang-Format
        run: |
          find . -name "*.cpp" -o -name "*.c" -o -name "*.h" | xargs clang-format -i

      # Step 4: Check for changes
      - name: Check for formatting changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Code formatting issues found. Please run Clang-Format.";
            exit 1;
          else
            echo "No formatting issues found.";
          fi
        continue-on-error: true # keep going if fails
    
  # static_analysis:
  #   runs-on: ubuntu-latest

  #   steps:
  #     # Step 1: Check out the repository
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
      
  #     # Step 2: Install the needed packages for linting
  #     - name: Set up cpplint
  #       run: sudo apt-get install -y cpplint
      
  #     # Step 3: Run the linter
  #     - name: Run cpp-lint
  #       run: |
  #         find . -name "*.cpp" -o -name "*.c" -o -name "*.h" | xargs cpplint

      # Step 4: Check for changes
      # - name: Check for linter changes
      #   run: |
      #     if [[ $(git status --porcelain) ]]; then
      #       echo "Code formatting issues found. Please run Clang-Format.";
      #       exit 1;
      #     else
      #       echo "No formatting issues found.";
      #     fi
      #   continue-on-error: true # keep going if fails

