name: Build, Format, and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # Step 2: Build the Docker image
      - name: Build Docker image
        run: docker build -t my-esp-image .

      # Step 3: Run container with entrypoint script
      - name: Run entrypoint script
        run: docker run --rm my-esp-image
