name: Build, Format, and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    container:
      image: bestbunsintown\my-esp-image:latest

    # container:
    #   image: espressif/idf:v5.2.1

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Step 3: Log in to Docker Hub (optional, if you need to push images)
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: idf.py build 
      
